version: '3.8'

services:
  admin_db:
    image: bitnami/postgresql:12
    container_name: admin_db
    restart: always
    ports:
      - "5434:5432"
    env_file: .env
    networks:
      - admin_net
    volumes:
      - admin_db_data:/bitnami/postgresql

#  admin_db:
#    container_name: admin_db
#    image: mysql:5.7.22
#    environment:
#      MYSQL_DATABASE: admin
#      MYSQL_USER: admin
#      MYSQL_PASSWORD: root
#      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
#
#    ports:
#      - 33068:3306
#    networks:
#      - admin_net
#    volumes:
#      - .dbdata:/var/lib/mysql

  admin_backend:
    container_name: admin_backend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - BROKER_HOST=admin_rabbit
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "
             python3 manage.py wait_for_db &&
             python3 manage.py collectstatic --noinput &&
             python3 manage.py makemigrations
             python3 manage.py migrate
             python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - admin_db
    networks:
      - admin_net

  # admin_mysqldb:
  #   container_name: admin_mysqldb
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=admin
  #     - MYSQL_USER=admin
  #     - MYSQL_PASSWORD=admin
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - .:/app
  #   networks:
  #     - admin_net

networks:
  admin_net:
    driver: bridge
volumes:
  admin_db_data:
#  admin_rabbit:
#    restart: on-failure
#    image: rabbitmq:3-management
#    container_name: admin_rabbit
#    hostname: rabbit
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=guest
#      - RABBITMQ_DEFAULT_VHOST=/
#      - BROKER_HOST=admin_rabbit
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - admin_net




